DROP VIEW IF EXISTS GR_ELEM_FACT_EXP_P100;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P0 AS
    SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
    OFFSET 0 ROWS FETCH NEXT 100 ROWS ONLY;

CREATE VIEW GR_ELEM_FACT_EXP_P100 AS
    SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
    OFFSET 100 ROWS FETCH NEXT 600 ROWS ONLY;

CREATE VIEW GR_ELEM_FACT_EXP_P1200 AS
    SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
    OFFSET 700 ROWS FETCH NEXT 1200 ROWS ONLY;

CREATE VIEW GR_ELEM_FACT_EXP_P2200 AS
    SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
    OFFSET 1200 ROWS FETCH NEXT 1000 ROWS ONLY;


CREATE VIEW GR_ELEM_FACT_EXP_P12200 AS
    SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
    OFFSET 2200 ROWS FETCH NEXT 10000 ROWS ONLY;

CREATE VIEW GR_ELEM_FACT_EXP_P22200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 12200 ROWS FETCH NEXT 10000 ROWS ONLY;

DROP VIEW IF EXISTS GR_ELEM_FACT_EXP_P32200;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P32200 WITH SCHEMABINDING AS
    SELECT
    dbo.De_Factura.FEx_Folio,
    dbo.De_FacturaDet.Fed_NoParte,
    CASE
        WHEN (dbo.De_FacturaDet.TiM_Clave) = 'EQ' THEN 'Retorno'
        WHEN (dbo.De_FacturaDet.TiM_Clave) = 'MAQ' THEN 'Retorno'
        WHEN (dbo.De_FacturaDet.TiM_Clave) = 'MP' THEN 'Mismo Estado'
        WHEN (dbo.De_FacturaDet.TiM_Clave) = 'PT' THEN 'Producto Terminado'
        WHEN (dbo.De_FacturaDet.TiM_Clave) = 'SUB' THEN 'Producto Terminado'
        WHEN (dbo.De_FacturaDet.TiM_Clave) = 'DESMP' THEN 'Producto Terminado'
    END AS TipoMatExp,
    CASE
        WHEN (MAX(dbo.De_FacturaDet.TiM_Clave)) = 'DESMP' THEN 'PRO'
        WHEN (MAX(dbo.De_FacturaDet.TiM_Clave)) = 'EQ' THEN 'ACT'
        WHEN (MAX(dbo.De_FacturaDet.TiM_Clave)) = 'MAQ' THEN 'ACT'
        WHEN (MAX(dbo.De_FacturaDet.TiM_Clave)) = 'MP' THEN 'MAT'
        WHEN (MAX(dbo.De_FacturaDet.TiM_Clave)) = 'PT' THEN 'PRO'
        WHEN (MAX(dbo.De_FacturaDet.TiM_Clave)) = 'SUB' THEN 'PRO'
        ELSE 'MAT'
    END AS NPTipo,
    MAX(dbo.De_FacturaDet.TiM_Clave) AS TiM_Clave,
    MAX(dbo.De_FacturaDet.Fed_DescripcionEsp) AS Fed_DescripcionEsp,
    MAX(dbo.De_FacturaDetUSA.Fed_DescripcionIng) AS Fed_DescripcionIng,
    SUM(dbo.De_FacturaDet.Fed_Cantidad) AS Fed_Cantidad,
    SUM(dbo.De_FacturaDet.Fed_PesoUnit) AS Fed_PesoUnit,
    SUM(dbo.De_FacturaDet.Fed_PesoNeto) AS Fed_PesoNeto,
    SUM(dbo.De_FacturaDet.Fed_PesoBru) AS Fed_PesoBru,
    COALESCE(MAX(dbo.De_PedimentoDet.Fra_FraccionUSA), '99999999') AS FRACUSA,
    COALESCE(MAX(dbo.De_PedimentoDet.Fra_Fraccion), '88888888') AS FRACCMX,
    MAX(dbo.De_FacturaDet.Med_Clave) AS Med_Clave,
    MAX(dbo.De_PedimentoDet.Med_Fraccion) AS Med_Fraccion,
    MAX(dbo.De_PedimentoDet.Ped_FactConvMx) AS Ped_FactConvMx,
    AVG(dbo.De_PedimentoDet.Ped_FactConvCom) AS Ped_FactConvCom,
    MAX(dbo.De_PedimentoDet.Ped_TipoTasaExp) AS Ped_TipoTasaExp,
    AVG(dbo.De_PedimentoDet.Ped_TasaAdv) AS Ped_TasaAdv,
    MAX(dbo.De_PedimentoDet.Pai_Origen) AS Pai_Origen,
    MAX(dbo.De_PedimentoDet.Pai_Destino) AS Pai_Destino,
    MAX(dbo.De_PedimentoDet.Pai_Comprador) AS Pai_Comprador,
    RIGHT(YEAR(MAX(dbo.De_Pedimento.Pex_FechaPago)), 2) + ' ' + LEFT(MAX(dbo.De_Pedimento.Adu_AduanaSecc), 2) + ' ' + MAX(dbo.De_Pedimento.AgP_Patente) + ' ' + MAX(dbo.De_Pedimento.Pex_Folio) AS NPedimentoExpGr,
    MAX(dbo.De_Pedimento.Pex_FechaPago) AS Pex_FechaPago,
    MAX(dbo.De_PedimentoDet.Ped_Secuencia) AS Ped_Secuencia,
    SUM(dbo.De_PedimentoDet.Ped_CostoUnit) AS Ped_CostoUnit,
    SUM(dbo.De_PedimentoDet.Ped_CostoUnitCom) AS Ped_CostoUnitCom,
    SUM(dbo.De_PedimentoDet.Ped_CostoUnitVA) AS Ped_CostoUnitVA,
    SUM(dbo.De_PedimentoDet.Ped_CostoTotUSD) AS Ped_CostoTotUSD,
    SUM(
        IIF(dbo.De_PedimentoDet.Ped_CostoUnit = 0 or (dbo.De_PedimentoDet.Ped_CostoUnitAdu / dbo.De_PedimentoDet.Ped_CostoUnit) = 0,
            0,
            dbo.De_PedimentoDet.Ped_CostoUnitVA /(
            dbo.De_PedimentoDet.Ped_CostoUnitAdu / dbo.De_PedimentoDet.Ped_CostoUnit
        ))
    ) AS LABOR,
    SUM(
        IIF(dbo.De_PedimentoDet.Ped_CostoUnit = 0 or (dbo.De_PedimentoDet.Ped_CostoUnitAdu / dbo.De_PedimentoDet.Ped_CostoUnit) = 0,
            0,
        dbo.De_PedimentoDet.Ped_CostoUnit - (
            dbo.De_PedimentoDet.Ped_CostoUnitVA /(
                dbo.De_PedimentoDet.Ped_CostoUnitAdu / dbo.De_PedimentoDet.Ped_CostoUnit
            )
        )
            )
    ) AS MATGRAB
FROM
    dbo.De_FacturaDet
    INNER JOIN dbo.De_Factura ON (
        dbo.De_FacturaDet.Fex_Consecutivo = dbo.De_Factura.FEx_Consecutivo
    )
    LEFT JOIN dbo.De_FacturaDetUSA ON (
        dbo.De_FacturaDet.Fex_Consecutivo = dbo.De_FacturaDetUSA.Fex_Consecutivo
    )
    INNER JOIN dbo.De_PedimentoDet ON (
        dbo.De_FacturaDet.Fex_Consecutivo = dbo.De_PedimentoDet.Fex_Consecutivo
    )
    INNER JOIN dbo.De_Pedimento ON(
        dbo.De_PedimentoDet.Pex_Consecutivo = dbo.De_Pedimento.Pex_Consecutivo
    ) GROUP BY dbo.De_Factura.FEx_Folio,
    dbo.De_FacturaDet.Fed_NoParte,
    CASE
        WHEN (dbo.De_FacturaDet.TiM_Clave) = 'EQ' THEN 'Retorno'
        WHEN (dbo.De_FacturaDet.TiM_Clave) = 'MAQ' THEN 'Retorno'
        WHEN (dbo.De_FacturaDet.TiM_Clave) = 'MP' THEN 'Mismo Estado'
        WHEN (dbo.De_FacturaDet.TiM_Clave) = 'PT' THEN 'Producto Terminado'
        WHEN (dbo.De_FacturaDet.TiM_Clave) = 'SUB' THEN 'Producto Terminado'
        WHEN (dbo.De_FacturaDet.TiM_Clave) = 'DESMP' THEN 'Producto Terminado'
    END
    ORDER BY FEx_Folio
    OFFSET 22200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE UNIQUE CLUSTERED INDEX IDX_GR0
   ON GR_ELEM_FACT_EXP_P32200 (FEx_Folio, Fed_NoParte, TipoMatExp);
GO

CREATE VIEW GR_ELEM_FACT_EXP_P42200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 32200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P52200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 42200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P62200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 52200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P72200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 62200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P82200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 72200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P92200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 82200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P102200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 92200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P112200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 102200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P122200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 112200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P132200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 122200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P142200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 132200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P152200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 142200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P162200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 152200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P172200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 162200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P182200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 172200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P192200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 182200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P202200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 192200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P212200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 202200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P222200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 212200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P232200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 222200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P242200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 232200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P252200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 242200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P262200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 252200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P272200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 262200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P282200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 272200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P292200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 282200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P302200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 292200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P312200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 302200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P322200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 312200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P332200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 322200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P342200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 332200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P352200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 342200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P362200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 352200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P372200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 362200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P382200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 372200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P392200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 382200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P402200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 392200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P412200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 402200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P422200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 412200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P432200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 422200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P442200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 432200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P452200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 442200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P462200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 452200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P472200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 462200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P482200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 472200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P492200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 482200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P502200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 492200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P512200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 502200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P522200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 512200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P532200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 522200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P542200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 532200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P552200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 542200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P562200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 552200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P572200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 562200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P582200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 572200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P592200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 582200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P602200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 592200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P612200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 602200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P622200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 612200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P632200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 622200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P642200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 632200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P652200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 642200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P662200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 652200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P672200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 662200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P682200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 672200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P692200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 682200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P702200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 692200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P712200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 702200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P722200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 712200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P732200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 722200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P742200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 732200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P752200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 742200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P762200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 752200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P772200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 762200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P782200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 772200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P792200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 782200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P802200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 792200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P812200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 802200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P822200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 812200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P832200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 822200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P842200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 832200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P852200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 842200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P862200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 852200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P872200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 862200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P882200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 872200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P892200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 882200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P902200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 892200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P912200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 902200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P922200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 912200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P932200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 922200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P942200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 932200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P952200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 942200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P962200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 952200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P972200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 962200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P982200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 972200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P992200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 982200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P1002200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 992200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P1012200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 1002200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO
CREATE VIEW GR_ELEM_FACT_EXP_P1022200 AS
		SELECT * FROM GR_ELEM_FACTEXPORT ORDER BY FEx_Folio
		OFFSET 1012200 ROWS FETCH NEXT 10000 ROWS ONLY;
GO