INSERT INTO AGENTESA (AG_RFC, AG_NOMBRE, AG_RAZONSOC, AG_DIRECCION, AG_NOEXT, AG_NOINT, AG_CP, AG_COLONIA, AG_CIUDAD, AG_EFEDERATIVA, AG_TELEFONO1, AG_TELEFONO2, AG_EMAIL, AG_PWEB, AG_FAXI, AG_FAXE, AG_CURP, AG_PAIS, AG_PATENTE, AG_DEFAULT) VALUES ('3', 'VICTOR HUGO GAMAS LUNA', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '3711', 'NO');

update AGENTESA
set AG_PATENTE = 3878
where AG_RFC = '16';

insert into AGENTESA (AG_RFC, AG_NOMBRE, AG_PATENTE)
values ('0', '', 3933);

insert into FARANCELARIAS (FR_FRACCION, FR_PAIS, FR_VALIDADESDE, FR_VALIDAHASTA)
values ('', 'USA', '2000-01-01', '3000-01-01');

insert into PEDIMENTOEXP (PE_PEDIMENTOEXP)
values ('');

insert into CLVPEDIM (CP_CLVPED)
values ('');

INSERT INTO ELEMFACTEXP (EE_NFACTEXP, EE_NPARTE, EE_TIPOMATEXP, EE_NPTIPO, EE_DESCESP, EE_DESCING, EE_TOTALMAT, EE_MATNONDUT, EE_MATDUTIABLE, EE_EMPNONDUT, EE_EMPDUTIABLE, EE_VALDUTIABLE, EE_OTRDUTIABLE, EE_EMPAQUE, EE_PESOUNIT, EE_PESOBRUTO, EE_PESONETO, EE_ARANCELUS, EE_ARANCELMX, EE_PESOEMPAQUE, EE_CANTEMPAQUE, EE_TIPOPARTE, EE_UMPARTE, EE_UMFRACCION, EE_FCONVERSION, EE_PAISDESTINO, EE_DESTINO, EE_NPARTEASOCIADO, EE_PEDIMENTOEXP, EE_FECHAPED, EE_NAFTA, EE_PAISORIGEN, EE_CLAVEFDA, EE_COSTOHR, EE_ESTANDARPROD, EE_ENSAMBLADOMX, EE_MATDUTUSD, EE_MATDUTMN, EE_MATNODUSD, EE_MATNODMN, EE_EMPUSD, EE_EMPMN, EE_AGREGUSD, EE_AGREGMN, EE_FPAGO, EE_SECUENCIAPEDEXP)
VALUES ('T1MP01511A1', 'PN-516824', 'Producto Terminado', 'PRO', 'CIRCUITO MODULAR', 'DISPOSITIVO DE MEDICIO', 1, 0, 8062, 0, 0, 0, 0, null, 0, 328, 0, '', '90303399', 0, 0, null, 'PCS', 'PCS', 0, 'USA', null, null, '20 24 3770 0001731', '2020-02-07 00:00:00.000', 'NO', 'USA', null, 0, 0, null, 0, 0, 0, 0, 0, 0, 0, 0, null, null);

INSERT INTO ELEMFACTEXP (EE_NFACTEXP, EE_NPARTE, EE_TIPOMATEXP, EE_NPTIPO, EE_DESCESP, EE_DESCING, EE_TOTALMAT, EE_MATNONDUT, EE_MATDUTIABLE, EE_EMPNONDUT, EE_EMPDUTIABLE, EE_VALDUTIABLE, EE_OTRDUTIABLE, EE_EMPAQUE, EE_PESOUNIT, EE_PESOBRUTO, EE_PESONETO, EE_ARANCELUS, EE_ARANCELMX, EE_PESOEMPAQUE, EE_CANTEMPAQUE, EE_TIPOPARTE, EE_UMPARTE, EE_UMFRACCION, EE_FCONVERSION, EE_PAISDESTINO, EE_DESTINO, EE_NPARTEASOCIADO, EE_PEDIMENTOEXP, EE_FECHAPED, EE_NAFTA, EE_PAISORIGEN, EE_CLAVEFDA, EE_COSTOHR, EE_ESTANDARPROD, EE_ENSAMBLADOMX, EE_MATDUTUSD, EE_MATDUTMN, EE_MATNODUSD, EE_MATNODMN, EE_EMPUSD, EE_EMPMN, EE_AGREGUSD, EE_AGREGMN, EE_FPAGO, EE_SECUENCIAPEDEXP) VALUES ('T2PT01915RT', 'PN-353740ÿ', 'Producto Terminado', 'PRO', 'CONTROLADOR DE VELOCIDAD PARA MOTORES', 'SMC-3 KONE 104 A KCM', 2, 0, 1160, 0, 0, 0, 0, null, 1, 2, 2, '', '85389099', 0, 0, null, 'PCS', 'PCS', 0, 'USA', null, null, '16 24 3770 6003522', '2016-03-16 00:00:00.000', 'NO', 'USA', null, 0, 0, null, 0, 0, 0, 0, 0, 0, 0, 0, null, null);
